### ISSUE TITLE
Overpass font cyrillization

### ISSUE THREAD

**Issue by AlexxNB** [AlexxNB/svelte3-translation-ru#11]
В главной репе решили, что шрифт Overpass идеально подходит для сайта. Рич пробовал несколько мильтиязычных шрифтов, но ничто не сравнилось с Overpass, https://github.com/sveltejs/svelte/issues/2276#event-2289874832.

Наш переведённый сайт не может использовать этот шрифт, поскольку там нет кириллических шрифтов, то вместо него отображается системный шрифт, который выглядит не так svelty, как хотелось бы.

Есть два варианта для решения этой проблемы:
1. Найти максимально похожий шрифт со свободной лицензией.
2. Нарисовать и добавить в шрифт Overpass русские глифы.

Я уже начал идти по 2 пути - https://github.com/AlexxNB/overpass-font-cyrillic
Проблема в том, что необходимо нарисовать как минимум 4 стиля шрифта разной толщины, а опыт рисования шрифтов у меня со вчерашнего дня начался.  Хотелось бы помощи (советом или делом) от более опытных людей.

**Comment by kubasovp** [comment]
1. Мне кажется, https://fonts.google.com/specimen/Open+Sans прям очень похож :)
2. Нарисовать действительно хороший шрифт, насколько я знаю, даже для профессионала нетривиальная задача, стоит ли игра свеч?..

**Comment by AlexxNB** [comment]
1. Нет, по стилю совершенно не то, особенно строчных букв. Плюс нету такого отлично тонкого стиля как у Overpass.
2. На самом деле я вчера попробовал и вроде бы что-то получается. Надо только в тему глубже въезжать. Кернинги там всякие и прочее. Добавлять глифы по имеющимся латинским всё-таки значительно проще, чем дизайнить новый шрифт.
![svelt](https://user-images.githubusercontent.com/10389013/56469378-ceff4b00-6441-11e9-9902-061ebc4749dd.png)

**Comment by AlexxNB** [comment]
Шрифты сделал, на сайт добавил, получилось сильно лучше, чем с системными шрифтами. Шрифт требует ещё немного работы с кернингами, но это уже мелочи.
![OverpassLightCyr](https://user-images.githubusercontent.com/10389013/56567185-05ada080-65bd-11e9-8ac6-38863fa82e82.png)

**Comment by lomeat** [comment]
Вышло кстати очень хорошо. Удивлен, что можно не имея опыта сделать красиво и читабельно за 3 дня. 
Интересно, а можно добавить кириллицу в оригинальный Overpass? Он же опен-сурсный

**Comment by AlexxNB** [comment]
Да, сайт без этого шрифта был совершенно иным. 
Добавлять в оригинал эти глифы я бы поостерегся, все-таки любительский уровень =)
