### ISSUE TITLE
Отсутствует гиф картинка

### ISSUE THREAD

**Issue by mi5ha6in** [AlexxNB/svelte3-translation-ru#16]
В разделе [Введение / Динамические атрибуты](https://ru.svelte.dev/tutorial/dynamic-attributes)  после выполнения задания должна появится гифка, но по url: https://ru.svelte.dev/tutorial/image.gif она отсутствует.

Гифка с англоязычной версии:
[Introduction / Dynamic Attributes](https://svelte.dev/tutorial/dynamic-attributes)
https://svelte.dev/tutorial/image.gif

**Comment by AlexxNB** [comment]
Спасибо! Займусь на днях актуализацией переводов и посмотрю, что случилось с картинкой.

**Comment by AlexxNB** [comment]
Картинка вернулась сама, после обновления до последней версии из репозитория оригинального сайта.
