### ISSUE TITLE
Неправильно работает ссылка.

### ISSUE THREAD

**Issue by denisnow** [AlexxNB/svelte3-translation-ru#29]
На странице https://ru.svelte.dev/tutorial/await-blocks в скрипте есть ссылка на `tutorial/random-number`. На русскоязычном сайте она выдаёт какой-то странный файл, а иногда просто нет соединения.

https://svelte.dev/tutorial/random-number
https://ru.svelte.dev/tutorial/random-number

**Comment by AlexxNB** [comment]
Да, действительно. Можно в fetch засунуть полный адрес на англоязычный вариант. Кажется, CORS там это позволяет.
Но сначала попробую разобраться, почему не работает на русском.

**Comment by Valexr** [comment]
Работаит уже 🤓
