### ISSUE TITLE
Неправильное отображение текста

### ISSUE THREAD

**Issue by denisnow** [AlexxNB/svelte3-translation-ru#33]
В подразделе https://ru.svelte.dev/tutorial/each-block-bindings
в поле 'input value' не помещается текст "прочитать учебник по Svelte"

**Comment by AlexxNB** [comment]
можно поставить "изучить учебник по Svelte"

**Comment by denisnow** [comment]
Изучить это синоним слова выучить, а как по мне "изучить учебник", это не совсем корректно. Хотя часто и говорят "выучить учебник" мне кажется, что правильно должно быть - выучить содержимое учебника. То есть учат что-то описываемое в этом учебнике, а не сам носитель.

**Comment by AlexxNB** [comment]
кажется, бОльшая проблема тут, что два однокоренных слова подряд идут. Что в моем, что в вашем варианте.
Может быть "Почитать учебник по Svelte"?

**Comment by denisnow** [comment]
Я тут поразмыслил, кажется "дочитать" самое то.

**Comment by AlexxNB** [comment]
Пожалуй

**Comment by denisnow** [comment]
Хорошо, я позже буду дальше читать и заодно проверять учебник, исправлю и отправлю запрос. Мне кажется это не существенно, так что нет срочности. Да и вообще ко мне можно на "ты"/"Ты" обращаться, в принципе вроде бы так принято, на сколько я заметил, в онлайн-среде разработчиков и просто айти, а может я ошибаюсь, не знаю. В принцыпе у меня тоже привычка обращаться на "Вы", но мне как-то подсказали, что безопаснее использовать инфинитив.

**Comment by denisnow** [comment]
Точнее не инфинитив а безличные глаголы.

**Comment by denisnow** [comment]
В общем не знаю как правильно это называется. Например вместо "Вы написали это неправильно" - "Это написано неправильно".

**Comment by denisnow** [comment]
Я передумал. Предлагаю "изучить Svelte".

**Comment by AlexxNB** [comment]
А мне все еще нравится "дочитать учебник по Svelte"

**Comment by denisnow** [comment]
Хорошо, пусть будет так. Просто мне кажется "изучить Svelte" более универсально, ведь скорее всего не все будут учить Svelte по официальной документации, некоторые могут в неё только заглянуть.

**Comment by denisnow** [comment]
Там ещё есть контроверсионный текст 'захватить мир'. Я например хочу спасти мир. Вы там может общаетесь с создателем Svelte, может можно это заменить или убрать? Я бы создал pull request но плохо владею английским.

**Comment by denisnow** [comment]
Даже не контроверсионный а провокационный, неуважительный что ли. Создается впечетление, что автор руководства считает нас то ли детьми то ли плохими людьми. Может быть я не прав, не знаю.

**Comment by AlexxNB** [comment]
> не все будут учить Svelte по официальной документации
Но позвольте, если будут не по учебнику учить, то и фразы этой не увидят, не так ли?

Не загоняйтесь слишком над тайными смыслами, это всего лишь документация, точнее её перевод.

**Comment by denisnow** [comment]
>Но позвольте, если будут не по учебнику учить, то и фразы этой не увидят, не так ли? Не загоняйтесь слишком над тайными смыслами, это всего лишь документация, точнее её перевод.
Какие ещё тайные смыслы? Меньше чуши пиши. Попасть в этот раздел учебника можно и с поисковика, вероятность еонечно не большая, поэтому я не настаивал.

**Comment by denisnow** [comment]
Точнее, желательно вообще чуши не пиши. :)

**Comment by denisnow** [comment]
Может тайные смыслы это про 'захватить мир'. Ну никаких тайных смыслов я там не вижу, зачем же так неадекватно реагировать? Есть два значения - можно захватить мир в коммерческом плане и можно захватить мир силой. Даже если предположить, что имеется ввиду первый вариант (а зачем нам эти домыслы?), то звучит как насмешка.

**Comment by denisnow** [comment]
А может просто слишком много плохого ассоциируется с этим словосочетанием - Гитлер, монополия, Дарт Вейдер, инвазия пришельцев - поэтому оно мне не нравится.

**Comment by denisnow** [comment]
Насчёт чуши и неадекватности, может я и не прав, может чего недопонял, вдруг что, сорян.

**Comment by denisnow** [comment]
А может имелось ввиду то, что люди, которые зайдут в этот раздел, допустим, из поисковика, и так поймут, что текст "доучить Svelte" составлен с мыслью о тех, кто учит Svelte по учебнику. Скорее всего поймут, а ещё больше вероятность, что даже не обратят на это внимания. Просто я наверное перфекционист, стараюсь сделать идеально, если есть такая возможность.

**Comment by denisnow** [comment]
Если уж на то пошло, то даже те кто уже знают Svelte и те кто написал уже первое приложение на нём, могут зайти в этот раздел. Так что по сути не важно прочитать, дочитать или почитать.

**Comment by denisnow** [comment]
"почитать" даже лучше дем "дочитать"

**Comment by denisnow** [comment]
Открою, чтобы ты не забыл исправить.
