### ISSUE TITLE
Лишний компонент в туториале

### ISSUE THREAD

**Issue by lomeat** [AlexxNB/svelte3-translation-ru#39]
В этапе [05/06](https://ru.svelte.dev/tutorial/dom-event-forwarding) есть лишний `CustomButton.svelte`. Который кстати является оригинальном в английском варианте. Непонятно зачем сделали на его место Fancy Button. 
В любом случае форкнул репозиторий, чтобы его удалить за ненужностью или вернуть исходный вариант. А оказалось, что в репозитории его нет. Но при этом в туториале он есть. Скрины ниже.

![56_1](https://user-images.githubusercontent.com/33469504/78464638-74afd680-76f4-11ea-86aa-54aa2e89e260.PNG)
![56_2](https://user-images.githubusercontent.com/33469504/78464641-76799a00-76f4-11ea-9923-9405b35b1ed7.PNG)
![56_3](https://user-images.githubusercontent.com/33469504/78464642-77aac700-76f4-11ea-9159-76cf04cb5c7e.PNG)

**Comment by AlexxNB** [comment]
CustomButton надо перенести из оригинального репозитория, перевести и удалить FancyButton. Просто в какой-то момент в оригинальной репе поменяли название файла, а перевод устанавливается патчем файлов поверх оригинального репозитория. Отсюда и появляются такие вещи. Сейчас у меня в разработке иной пайплайн перевода - который будет доступен переводчикам из других стран тоже. Там слежение за такими вещами учтено.

**Comment by AlexxNB** [comment]
fixed in https://github.com/AlexxNB/svelte3-translation-ru/pull/41
