### ISSUE TITLE
Изменить атрибут lang у тега html 

### ISSUE THREAD

**Issue by Olovyannikov** [AlexxNB/svelte3-translation-ru#63]
Сейчас при переходе на сайт ru.svelte.dev различные встроенные в браузер транслейторы просят перевести русский язык с английского на русский, что, разумеется, странно. 

Решение простое - lang="ru" :) 

Маленькое замечание, но будет приятно, если примете к сведению.

**Comment by AlexxNB** [comment]
Спасибо, ценный совет =) Сделаем.
