### ISSUE TITLE
Совет о реализации переводов на другие языки

### ISSUE THREAD

**Issue by jlkiri** [AlexxNB/svelte3-translation-ru#64]
Привет! Я не нашел другого способа связаться с вами, кроме как здесь. 

Я живу в Японии и хочу организовать группу по переводу документации Svelte на японский. Мне было бы интересно узнать как вам удалось опубликовать русскую версию сайта как субдомен svelte.dev. Какие мне потребуются для этого права? Похоже что команда Svelte не сильно заинтересована в официальных переводах, и я пока не нашел ответа в официальном Discord.

**Comment by AlexxNB** [comment]
Сам процесс адаптации примерно тут описал: https://github.com/AlexxNB/svelte3-translation-ru/issues/56

Домен изначально был свой, потом когда документация уже была готова, связался с Ричем в Дискорте и мы договорились, что он сделает нам поддомен. Без готового результата, думаю нет смысла свзяываться на эту тему. 

Команда Svelte в целом не против, просто сначала они хотелеи завести [i18n в Sapper](https://github.com/sveltejs/sapper/issues/576#issuecomment-757129136), чтобы уже на её основе сделать мультиязычный сайт, но все погрязло в обсуждениях и Sapper уже вроде как приговорен.

**Comment by jlkiri** [comment]
Спасибо! Попробую сделать так же.
