### ISSUE TITLE
Mapbox не отображает карту (403)

### ISSUE THREAD

**Issue by WacesRedky** [AlexxNB/svelte3-translation-ru#73]
На [странице с картой MapBox](https://ru.svelte.dev/tutorial/context-api) подложка в виде самой карты не отображается. В консоли ошибки 403. Вероятно они связаны с тем, что ACCESS_TOKEN более не актуален.

В [английской версии](https://svelte.dev/tutorial/context-api) всё отображается как надо.

**Comment by AlexxNB** [comment]
![image](https://user-images.githubusercontent.com/10389013/111024045-967a0900-83ed-11eb-8c23-c5893e65398f.png)
Показывается вроде с текущим токеном

**Comment by AlexxNB** [comment]
На всякий случай обновил токен, на тот который используется в англоязычной версии.
